POST /conversationmpt HTTP/1.1
Content-Type: application/json
X-Rapidapi-Key: 4749eed77fmsh282e13aab241c01p1c733djsn8a439686b347
X-Rapidapi-Host: open-ai21.p.rapidapi.com
Host: open-ai21.p.rapidapi.com
Content-Length: 139

{
    "messages": [
        {
            "role": "user",
            "content": "hello"
        }
    ],
    "web_access": false
}
